name: Upcoming Reservations

on:
  workflow_dispatch:
  schedule:
  # ^^^ Github's scheduler is SUPER INACCURATE with delays of dozens of minutes (sometimes more than an hour...)
   - cron: '51 20 * * *'
   # So 20:51 UTC is either 12:51pm or 1:51pm Pacific (depending on daylights savings)

jobs:
  read_all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Those are the default permissions for any Github Actions job, but we make sure to leave out `pages: write` and `id-token: write` so that we can be sure this step isn't deploying to Github Pages itself
    environment: "Prod (Lifetime Activities Sunnyvale)"
    steps:
    - name: Checkout repository
      timeout-minutes: 4
      uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Install Playwright
      timeout-minutes: 4
      run: sh i7-10810U_chatreey/dev-github/reinstall_playwright.sh
    - name: List any reservations we can find
      timeout-minutes: 30
      working-directory: ./i7-10810U_chatreey/app_courtreserve_com
      run: npx --no-install playwright test main/example.spec.ts --grep 'read upcoming reservations'
      env:
        READ_USERNAMES: ${{ secrets.YIFEI }},${{ secrets.RAYMOND }},${{ secrets.ANTHONY }}
        READ_PASSWORDS: ${{ secrets.LOGIN4 }},${{ secrets.LOGIN_RAYMOND_NANA }},${{ secrets.LOGIN_PROD }}
        WAIVERCHECK_USERNAMES: ${{ secrets.NANA }}
        WAIVERCHECK_PASSWORDS: ${{ secrets.LOGIN_RAYMOND_NANA }}
    - uses: actions/upload-pages-artifact@v3
      with:
        path: i7-10810U_chatreey/app_courtreserve_com/upcoming_reservations
    # ^^^ This step will create a Github Artifact with a very specific filename
    - name: Upload screenshots if problems found
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: screenshots_DEBUG-playwright-${{ github.job }}
        path: |
          i7-10810U_chatreey/app_courtreserve_com/*.png
          i7-10810U_chatreey/app_courtreserve_com/test-results/example-read-upcoming-reservations-chromium/*.png
          i7-10810U_chatreey/app_courtreserve_com/test-results/example-read-upcoming-reservations-chromium/*.md
        overwrite: false
        compression-level: 9
        retention-days: 11
        # [!IMPORTANT]
        # Always set retention-days (or else we'll run out of Github Actions space!!)


  deploy:
    needs: read_all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      # I guess these two environment variables ensure that everything makes sense when it comes to the `id: deployment` step below
    runs-on: ubuntu-latest
    # Permissions are needed to deploy Github Pages
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
    # This will look for a Github Artifact of a very specific filename, and publish it accordingly
    # e.g. https://yusizee.github.io/nixos-config/lifetime_activities.txt
    # Manage this further in Github: Settings → Pages
    # e.g. https://github.com/yuzisee/nixos-config/settings/pages
    # [PERMISSIONS]
    # In https://github.com/yuzisee/nixos-config/settings/environments you will also see a `github-pages` environment

